language: go
go:
  - 1.11

# Use container-based infrastructure
dist: trusty
sudo: required

services:
  - docker

env:
  DOCKER_IMAGE: m1kola/shipsterbot

# Install project dependencies
install:
  - make vendor

script:
  # Run tests
  - make test

  # Build a docker image
  - docker build -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
  - docker images $DOCKER_IMAGE

deploy:
  provider: script
  on:
    branch: master
  script: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" && docker push $DOCKER_IMAGE
