language: go
go:
  - 1.9

# Use container-based infrastructure
dist: trusty
sudo: required

services:
  - docker


# Install project dependencies
install:
  - make vendor

script:
  # Run tests
  - make test

  # Build a docker image
  - docker build -t m1kola/shipsterbot .
  - docker images
